"use client";
import Link from "next/link";import {useEffect,useState} from "react";import XingyueyangHeader from "@/components/XingyueyangHeader";import FloatingAI from "@/components/FloatingAI";import Reveal from "@/components/Reveal";import {company} from "@/lib/xingyueyang";
const industries=["炼油","化工","煤电","制药","烟草","农业"];
const solutions=[["01","在线检测","将光谱检测能力部署到生产现场，实现连续感知与过程分析。","ONLINE"],["02","科学仪器","台式、便携、手持与在线设备覆盖不同检测形态。","INSTRUMENT"],["03","智能算法","把光谱信号转换为质量、成分与过程判断信息。","ALGORITHM"],["04","系统连接","为 MES、ERP 与企业数据平台保留标准化集成方向。","CONNECT"]];
export default function Home(){
 const [products,setProducts]=useState<any[]>([]),[news,setNews]=useState<any[]>([]),[cases,setCases]=useState<any[]>([]);
 useEffect(()=>{Promise.all([fetch("/api/products?featured=1",{cache:"no-store"}).then(r=>r.json()),fetch("/api/news?limit=3",{cache:"no-store"}).then(r=>r.json()),fetch("/api/cases?featured=1",{cache:"no-store"}).then(r=>r.json()).catch(()=>({cases:[]}))]).then(([p,n,c])=>{setProducts(p.products||[]);setNews(n.news||[]);setCases(c.cases||[])}).catch(()=>{})},[]);
 const lead=products.find(p=>p.image_url)||products[0];
 return <main className="min-h-screen bg-[#f4f5f6]"><XingyueyangHeader/>
 <section className="relative overflow-hidden bg-[#07111f] text-white">
  <div className="absolute inset-0 opacity-70 [background-image:linear-gradient(rgba(255,255,255,.028)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.028)_1px,transparent_1px)] [background-size:54px_54px]"/>
  <div className="absolute right-[4%] top-[7%] h-[420px] w-[420px] rounded-full border border-amber-300/10 lg:h-[520px] lg:w-[520px]"/><div className="absolute right-[12%] top-[15%] h-[280px] w-[280px] rounded-full border border-cyan-200/10 lg:h-[360px] lg:w-[360px]"/>
  <div className="relative mx-auto grid min-h-0 max-w-7xl items-center gap-10 px-5 py-14 sm:py-16 lg:min-h-[680px] lg:grid-cols-[.94fr_1.06fr] lg:gap-14 lg:px-8 lg:py-20">
   <Reveal><p className="text-[11px] font-bold tracking-[.25em] text-amber-400">MOLECULAR SPECTROSCOPY · INDUSTRIAL INTELLIGENCE</p><h1 className="mt-7 text-[42px] font-semibold leading-[.98] tracking-[-.055em] sm:text-5xl md:text-6xl lg:text-7xl lg:tracking-[-.065em]
">看见工业过程中的<br/><span className="text-amber-400">分子信息。</span></h1><p className="mt-6 max-w-xl text-[15px] leading-7 sm:mt-8 sm:text-[16px] sm:leading-8
 text-slate-300">从近红外、红外与拉曼感知，到在线分析与工业系统连接。星玥阳将科学仪器、算法和现场应用组合成完整检测路径。</p><div className="mt-8 grid grid-cols-2 gap-2.5 sm:flex sm:flex-wrap sm:gap-3
"><Link href="/products" className="rounded-full bg-amber-400 px-6 py-3 text-sm font-bold text-slate-950 transition hover:-translate-y-0.5">探索产品系统</Link><Link href="/cases" className="rounded-full border border-white/20 px-6 py-3 text-sm transition hover:bg-white/5">查看工程案例</Link></div><div className="mt-10 grid max-w-xl grid-cols-1 divide-y divide-white/10 border-t sm:mt-14 sm:grid-cols-3 sm:divide-x sm:divide-y-0 border-white/10 pt-5"><div><b className="text-sm">NIR · IR · Raman</b><span className="mt-1 block text-xs text-slate-500">光谱技术</span></div><div><b className="text-sm">Offline → Online</b><span className="mt-1 block text-xs text-slate-500">检测形态</span></div><div><b className="text-sm">AI · MES Ready</b><span className="mt-1 block text-xs text-slate-500">数字连接</span></div></div></Reveal>
   <Reveal delay={100}><div className="relative mx-auto w-full max-w-[500px] lg:max-w-[560px]"><div className="rounded-[34px] border border-white/10 bg-white/[.045] p-4 shadow-[0_30px_90px_rgba(0,0,0,.18)] backdrop-blur sm:p-5"><div className="flex justify-between text-[10px] tracking-[.16em] text-slate-400"><span>ONLINE ANALYSIS / INDUSTRIAL SYSTEM</span><span className="text-emerald-300">● ONLINE</span></div><div className="relative mt-5 aspect-[4/3] overflow-hidden rounded-[24px] bg-white/[.035]"><div className="absolute inset-0 opacity-50 [background-image:linear-gradient(rgba(255,255,255,.05)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.05)_1px,transparent_1px)] [background-size:30px_30px]"/>{lead?.image_url?<img src={lead.image_url} alt={lead.name} className="relative z-10 h-full w-full object-contain p-6 sm:p-8"/>:<div className="relative z-10 grid h-full place-items-center text-sm text-slate-500">设备主图由 Product CMS 管理</div>}<svg viewBox="0 0 600 120" className="absolute bottom-3 left-4 z-20 h-20 w-[calc(100%-2rem)] opacity-70 sm:h-24"><path d="M0 80 C55 80 60 30 110 65 S170 95 215 44 S290 88 330 62 S390 24 430 65 S510 86 600 42" fill="none" stroke="rgb(251 191 36)" strokeWidth="2"/></svg></div><div className="mt-5 flex items-end justify-between"><div><div className="text-xs font-bold tracking-[.12em] text-amber-400">{lead?.model||"PRODUCT SYSTEM"}</div><div className="mt-1 text-xl font-semibold">{lead?.name||"工业在线监测系统"}</div></div><span className="rounded-full border border-white/10 px-3 py-1.5 text-[9px] tracking-[.12em] text-slate-400">SPECTRAL DATA</span></div></div></div></Reveal>
  </div>
 </section>
 <section className="border-b bg-white"><div className="mx-auto grid max-w-7xl grid-cols-3 px-5 md:grid-cols-6 lg:px-8">{industries.map(x=><div key={x} className="border-r border-slate-100 py-5 text-center text-sm font-semibold last:border-0">{x}</div>)}</div></section>

 <section className="bg-white py-28"><div className="mx-auto max-w-7xl px-5 lg:px-8"><Reveal><div className="grid gap-10 lg:grid-cols-[.72fr_1.28fr]"><div><span className="xy-kicker">INDUSTRIAL PLATFORM</span><h2 className="mt-5 text-3xl font-semibold tracking-[-.04em] sm:text-4xl lg:text-5xl lg:tracking-[-.055em]">不止检测设备。<br/>连接工业现场。</h2><p className="mt-6 max-w-md text-sm leading-7 text-slate-500">从仪器、算法、在线检测到企业系统连接，形成可扩展的工业检测平台。</p></div><div className="grid gap-3 md:grid-cols-2">{solutions.map(([n,t,d,e])=><Link href="/solutions" key={n} className="group block rounded-[28px] border border-slate-200 bg-[#f7f8f9] p-6 text-slate-900 transition duration-300 hover:-translate-y-1 hover:bg-white hover:shadow-xl"><div className="flex justify-between"><span className="text-xs font-bold text-amber-600">{n}</span><span className="text-[9px] tracking-[.18em] text-slate-400">{e}</span></div><h3 className="mt-12 text-2xl font-semibold">{t}</h3><p className="mt-3 text-sm leading-7 text-slate-500">{d}</p><div className="mt-7 text-sm font-bold">了解方案 →</div></Link>)}</div></div></Reveal></div></section>

 <section className="bg-[#edf0f2] py-28"><div className="mx-auto max-w-7xl px-5 lg:px-8"><Reveal><div className="flex flex-col items-start gap-4 sm:flex-row sm:items-end sm:justify-between"><div><span className="xy-kicker">PRODUCT SYSTEMS</span><h2 className="mt-4 text-3xl font-semibold sm:text-4xl tracking-[-.04em] md:text-5xl">在线监测产品系统</h2></div><Link href="/products" className="text-sm font-bold text-slate-900">全部产品 →</Link></div></Reveal><div className="mt-10 grid gap-5 lg:grid-cols-3">{products.map((p,i)=><Reveal key={p.id||p.slug} delay={i*80}><Link href={`/products/${p.slug}`} className="group block overflow-hidden rounded-[30px] border border-slate-200 bg-white text-slate-900"><div className="relative aspect-[4/3] overflow-hidden bg-[#e4e8eb]"><div className="absolute inset-0 [background-image:linear-gradient(rgba(15,23,42,.04)_1px,transparent_1px),linear-gradient(90deg,rgba(15,23,42,.04)_1px,transparent_1px)] [background-size:30px_30px]"/>{p.image_url?<img src={p.image_url} alt={p.name} className="relative z-10 h-full w-full object-contain p-7 transition duration-700 group-hover:scale-[1.04]"/>:<div className="relative z-10 grid h-full place-items-center text-sm text-slate-400">设备主图待上传</div>}<span className="absolute left-5 top-5 z-20 rounded-full bg-[#07101d] px-3 py-1.5 text-[9px] tracking-[.15em] text-white">ONLINE SYSTEM</span></div><div className="p-6"><div className="text-xs font-bold tracking-[.14em] text-amber-600">{p.model}</div><h3 className="mt-2 text-xl font-semibold">{p.name}</h3><p className="mt-3 line-clamp-2 text-sm leading-6 text-slate-500">{p.subtitle||p.description}</p><div className="mt-7 flex items-center justify-between text-sm font-bold"><span>查看系统</span><span>→</span></div></div></Link></Reveal>)}</div></div></section>

 <section className="bg-[#07101d] py-28 text-white"><div className="mx-auto max-w-7xl px-5 lg:px-8"><Reveal><span className="text-[10px] font-bold tracking-[.22em] text-amber-400">DATA TO DECISION</span><h2 className="mt-5 max-w-4xl text-3xl font-semibold sm:text-4xl tracking-[-.045em] md:text-6xl">让检测结果进入生产系统，<br/>而不是停留在仪器屏幕里。</h2><div className="mt-14 grid gap-2 md:grid-cols-5">{["光谱感知","实时分析","质量判断","MES / ERP","生产决策"].map((x,i)=><div key={x} className="rounded-[22px] border border-white/10 bg-white/[.035] p-5"><div className="text-[10px] text-amber-400">0{i+1}</div><div className="mt-5 font-semibold md:mt-12">{x}</div><div className="mt-2 text-[10px] tracking-[.15em] text-slate-600">{i<4?"DATA FLOW →":"ACTION"}</div></div>)}</div></Reveal></div></section>

 <section className="bg-white py-28"><div className="mx-auto max-w-7xl px-5 lg:px-8"><Reveal><div className="flex flex-col items-start gap-4 sm:flex-row sm:items-end sm:justify-between"><div><span className="xy-kicker">ENGINEERING CASES</span><h2 className="text-3xl font-semibold sm:text-4xl">工业现场，不只参数表。</h2></div><Link href="/cases" className="text-sm font-bold">工程案例 →</Link></div></Reveal><div className="mt-10 grid gap-5 lg:grid-cols-3">{cases.length?cases.slice(0,3).map((c,i)=><Reveal key={c.id} className={i===0?"lg:col-span-2":""}><Link href={`/cases/${c.slug}`} className="group block overflow-hidden rounded-[28px] bg-[#f4f5f6]">{c.image_url?<img src={c.image_url} className={`${i===0?"aspect-[16/7]":"aspect-[16/9]"} w-full object-cover transition duration-700 group-hover:scale-[1.025]`} alt={c.title}/>:<div className={`${i===0?"aspect-[16/7]":"aspect-[16/9]"} grid place-items-center bg-slate-200 text-sm text-slate-400`}>Case CMS 上传现场图片</div>}<div className="p-6"><div className="text-xs font-bold text-amber-600">{c.industry||"ENGINEERING"}</div><h3 className="mt-3 text-2xl font-semibold">{c.title}</h3><p className="mt-3 line-clamp-2 text-sm text-slate-500">{c.summary}</p></div></Link></Reveal>):<div className="lg:col-span-3 rounded-[28px] border border-dashed p-12 text-center text-sm text-slate-400">Dashboard 发布工程案例后，这里自动形成现场展示。</div>}</div></div></section>

 <section className="border-t bg-[#fafafa] py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><Reveal><div className="flex flex-col items-start gap-4 sm:flex-row sm:items-end sm:justify-between"><div><span className="xy-kicker">COMPANY NEWS</span><h2 className="mt-4 text-3xl font-semibold sm:text-4xl">公司动态</h2></div><Link href="/news" className="text-sm font-bold">新闻中心 →</Link></div></Reveal><div className="mt-9 divide-y border-y border-slate-200">{news.length?news.map((n,i)=><Reveal key={n.id} delay={i*60}><Link href={`/news/${n.slug}`} className="grid gap-4 py-7 transition hover:pl-2 md:grid-cols-[160px_1fr_80px] md:items-center"><div className="text-sm font-bold text-amber-600">{n.published_at?new Date(n.published_at).toLocaleDateString("zh-CN"):"NEWS"}</div><div><h3 className="text-xl font-semibold">{n.title||"公司动态"}</h3><p className="mt-2 line-clamp-1 text-sm text-slate-500">{n.summary||n.excerpt||"来自星玥阳科技的最新动态。"}</p></div><div className="text-right text-xl">→</div></Link></Reveal>):<div className="py-12 text-sm text-slate-400">Company News CMS 发布后自动展示。</div>}</div></div></section>

 <section className="bg-amber-400"><div className="mx-auto grid max-w-7xl gap-8 px-5 py-16 lg:grid-cols-[1fr_auto] lg:items-center lg:px-8"><div><span className="text-[10px] font-bold tracking-[.2em]">TECHNICAL CONSULTATION</span><h2 className="mt-3 text-3xl font-semibold tracking-[-.035em]">把检测需求带到真实工业现场。</h2></div><Link
  href="/contact"
  className="rounded-full bg-[#07101d] px-7 py-3.5 text-sm font-bold !text-white transition hover:bg-[#162235]"
>
  联系技术团队 →
</Link></div></section>
 <footer className="bg-white"><div className="mx-auto grid max-w-7xl gap-8 px-5 py-12 lg:grid-cols-3 lg:px-8"><div><b>{company.nameZh}</b><div className="mt-1 text-[10px] tracking-[.2em] text-slate-400">UNIVERSE TECH</div><p className="mt-4 text-sm leading-7 text-slate-500">{company.tagline}</p></div><div className="text-sm leading-7 text-slate-500"><b className="text-slate-950">业务联系</b><div className="mt-3">{company.contact} · {company.phone}</div><div>业务 QQ：{company.qq}</div></div><div className="text-sm leading-7 text-slate-500"><b className="text-slate-950">公司地址</b><div className="mt-3">{company.address}</div></div></div></footer>
 <FloatingAI/></main>
}
